project:
  name: enmap-pansharpening

input:
  directory: "data"
  enmap_data_root: "data/enmap/ENMAP_HSI_L2A"
  sen2_data_root: "data/sentinel2/sentinel-2-l2a"

search:
  min_overlap: 70
sentinel2_search:
  max_cloud_cover: 20
  max_time_difference_hours: 1

sentinel2_download:
  download_full_sen2_item: False

processing:
  crop_to_aoi: True

pansharpening:
  chunk_size: 128
  padding_size: 16
  
output_directory: "outputs"
output_COG: False

cleanup_data_tmp: False
request_delay_seconds: 2

thumbnail_size: [343, 343]

storage:
  s3:
    enabled: False
    bucket: "private-terravision"
    prefix: "enmap-l2a-pansharpened-gsa-10m"

stac:
  enabled: False
  collection_id: "enmap-l2a-pansharpened-gsa-10m"