services:
  enmap_pansharp:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env
      # DLR_USERNAME=
      # DLR_PASSWORD=
      # CDSE_USERNAME=
      # CDSE_PASSWORD=
      # ICCS_USERNAME=
      # ICCS_PASSWORD
      # AWS_ACCESS_KEY_ID=
      # AWS_SECRET_ACCESS_KEY


    image: enmap_pansharp:latest
    container_name: enmap_pansharp

    volumes:
      - .:/app
      - ./data:/data

    environment:
      PYTHONUNBUFFERED: "1"

    entrypoint: ["python", "src/main.py"]

    command: ["--user_input", "${USER_INPUT:-aoi.geojson}", "--config", "${CONFIG_FILE:-}"]