services:
  enmap_pansharp:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    image: enmap_pansharp:latest
    container_name: enmap_pansharp

    volumes:
      - .:/app
      - ./data:/data

    environment:
      PYTHONUNBUFFERED: "1"

    entrypoint: ["python", "src/main.py"]

    command: ["--user_input", "${USER_INPUT:-aoi.geojson}", "--config", "${CONFIG_FILE:-}"]