project:
  name: sentinel3-lst-sharpening

input:
  directory: "/data/sentinel3slstr"

search:
  max_cloud_cover: 10
  min_overlap: 80
  max_time_difference_hours: 1

thumbnail_size: [343, 343]

cleanup_data_tmp: False
  
output:
  directory: "outputs"
  format: "GeoTIFF"

output_COG: True

storage:
  s3:
    enabled: True
    bucket: 'private-terravision'
    prefix: "sentinel3-lst-ntc-thermal-sharpened-10m"

stac:
  enabled: True
  collection_id: "sentinel3-lst-ntc-thermal-sharpened-10m"